#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "penpot"
name = "Penpot"
description.en = "Design and prototyping platform"
description.fr = "Plateforme de conception et de prototypage"

version = "2.17.2~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "MPL-2.0"
website = "https://penpot.app/"
admindoc = "https://help.penpot.app/technical-guide/"
userdoc = "https://help.penpot.app/user-guide/"
code = "https://github.com/penpot/penpot"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = true
sso = false

disk = "500M"
ram.build = "500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/orhtej2/penpot-binary/releases/download/2.17.2-extracted/penpot-frontend-extracted.tar.gz"
    sha256 = "00d8e942bafafd5e2539b96c850f0e3f5254b4a8b4d58492181975793aca3c85"
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/penpot-binary"
    autoupdate.asset = "penpot-frontend-extracted\\.tar\\.gz$"
    autoupdate.version_regex = "(\\d+\\.\\d+\\.\\d+)-extracted"

    [resources.sources.backend]
    url = "https://github.com/orhtej2/penpot-binary/releases/download/2.17.2-extracted/penpot-backend-extracted.tar.gz"
    sha256 = "ad27323eb843b1cdff6fcf3d6ce6b9e963e57e02b202d7cf5a863907070dc3ca"
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/penpot-binary"
    autoupdate.asset = "penpot-backend-extracted\\.tar\\.gz$"
    autoupdate.version_regex = "(\\d+\\.\\d+\\.\\d+)-extracted"

    [resources.sources.exporter]
    amd64.url = "https://github.com/orhtej2/penpot-binary/releases/download/2.17.2-extracted/penpot-exporter-amd64-extracted.tar.gz"
    amd64.sha256 = "57819ab504b8c0c2fd271a73a9dd8d1bc942ff8ee4a65a6f2b75d7c5a456f4d3"
    arm64.url = "https://github.com/orhtej2/penpot-binary/releases/download/2.17.2-extracted/penpot-exporter-arm64-extracted.tar.gz"
    arm64.sha256 = "1e85433d325fdc2200efbd69946323e5017c2eed90a19284bc35917c23107c22"
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/penpot-binary"
    autoupdate.asset.amd64 = "penpot-exporter-amd64-extracted\\.tar\\.gz$"
    autoupdate.asset.arm64 = "penpot-exporter-arm64-extracted\\.tar\\.gz$"
    autoupdate.version_regex = "(\\d+\\.\\d+\\.\\d+)-extracted"

    [resources.sources.jre]
    amd64.url = "https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.4%2B7/OpenJDK25U-jre_x64_linux_hotspot_25.0.4_7.tar.gz"
    amd64.sha256 = "aed3915f8facc0c80733ab2448bb0df4b494a36a2c5759e9a6e1eb979720f2b3"
    arm64.url = "https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25.0.4%2B7/OpenJDK25U-jre_aarch64_linux_hotspot_25.0.4_7.tar.gz"
    arm64.sha256 = "1f2644427000316bc431df3389504551ed7464fe8486bf6b4f1130af9ffc8f55"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
    autoupdate.upstream = "https://github.com/adoptium/temurin25-binaries"
    autoupdate.asset.amd64 = "OpenJDK.*-jre_x64_linux_hotspot_.*\\.tar\\.gz$"
    autoupdate.asset.arm64 = "OpenJDK.*-jre_aarch64_linux_hotspot_.*\\.tar\\.gz$"

    [resources.sources.imagemagick]
    amd64.url = "https://github.com/orhtej2/imagemagick-binary/releases/download/7.1.2-30/imagemagick-7.1.2-30-linux-amd64.tar.gz"
    amd64.sha256 = "ed1a7b8427b60471967631d1b0c396fd1c22f10d8d377221f75eacbc3810bdb1"
    arm64.url = "https://github.com/orhtej2/imagemagick-binary/releases/download/7.1.2-30/imagemagick-7.1.2-30-linux-arm64.tar.gz"
    arm64.sha256 = "b7fb04b7e122832c3eea470f504af7ad8d35e1f50a0c55d985886c5e87f20964"
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/imagemagick-binary"
    autoupdate.asset.amd64 = "imagemagick-\\d+\\.\\d+\\.\\d+-\\d+-linux-amd64\\.tar\\.gz$"
    autoupdate.asset.arm64 = "imagemagick-\\d+\\.\\d+\\.\\d+-\\d+-linux-arm64\\.tar\\.gz$"

    [resources.sources.imagemagick-policy]
    url = "https://raw.githubusercontent.com/penpot/penpot/034bab99c9abcbf5aadf7418ef40747925398ae3/docker/images/files/imagemagick-policy.xml"
    sha256 = "f5d9a98218665d8afe11a6ed772be901e1c84ddcbba7c3a9c9e1d6a32b004012"
    format = "whatever"
    extract = false
    rename = "policy.xml"
    
    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    subdirs = ["assets"]
    group = "www-data:rx"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
        [resources.ports.exporter]

    [resources.apt]
    packages = [
        "postgresql",
        "redis",
        "tzdata",
        "locales",
        "ca-certificates",
        "fontconfig",
        "xz-utils",
        "imagemagick",
        "ghostscript",
        "netpbm",
        "poppler-utils",
        "potrace",
        "libasound2",
        "libatk1.0-0",
        "libatk-bridge2.0-0",
        "libatomic1",
        "libcairo2",
        "libcups2",
        "libdbus-1-3",
        "libexpat1",
        "libfontconfig1",
        "libgcc1",
        "libglib2.0-0",
        "libgtk-3-0",
        "libnspr4",
        "libpango-1.0-0",
        "libpangocairo-1.0-0",
        "libx11-6",
        "libx11-xcb1",
        "libxcb1",
        "libxcb-dri3-0",
        "libxcomposite1",
        "libxcursor1",
        "libxdamage1",
        "libxext6",
        "libxfixes3",
        "libxi6",
        "libxrandr2",
        "libxrender1",
        "libxshmfence1",
        "libxss1",
        "libxtst6",
        "fonts-liberation",
        "libnss3",
        "libgbm1",
        "webp",
        "rlwrap",
        "woff-tools",
        "woff2",
        "python3",
        "python3-tabulate",
        "fontforge",
        "rsync"
    ]

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
