#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

redis_db=$(ynh_redis_get_free_db)
secret_key=$(ynh_string_random --length=40)
main_domain=$(yunohost domain list --output-as plain | grep -A1 -e '#main' | tail -n 1)

ynh_app_setting_set --key=redis_db --value=$redis_db
ynh_app_setting_set --key=secret_key --value=$secret_key
ynh_app_setting_set --key=main_domain --value=$main_domain
ynh_app_setting_set_default --key=telemetry_enabled --value=false

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_setup_source --dest_dir="$install_dir/jre" --source_id="jre"

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/backend" --source_id="backend"
ynh_setup_source --dest_dir="$install_dir/exporter" --source_id="exporter"
chown -R $app:$app "$install_dir"

ynh_setup_source --dest_dir="$install_dir/frontend"
chown -R $app:www-data "$install_dir/frontend"
chgrp www-data $install_dir

chmod -R o-rwx "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd --template="backend.service" --service="$app-backend"
yunohost service add $app-backend --log="/var/log/$app/$app-backend.log"

ynh_config_add_systemd --template="exporter.service" --service="$app-exporter"
yunohost service add $app-exporter --log="/var/log/$app/$app-exporter.log"

# Use logrotate to manage application logfile(s)
mkdir -p /var/log/$app
touch /var/log/$app/$app-backend.log
touch /var/log/$app/$app-exporter.log

ynh_config_add_logrotate "/var/log/$app/$app-backend.log"
ynh_config_add_logrotate "/var/log/$app/$app-exporter.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Updating database configuration..."

ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"

ynh_script_progression "Adding app's configuration file..."

ynh_config_add --template="config.js" --destination="$install_dir/frontend/js/config.js"
chmod 755 "$install_dir/frontend/js/config.js"
chown $app:www-data "$install_dir/frontend/js/config.js"

ynh_config_add --template="environ" --destination="$install_dir/backend/environ"

ynh_config_add --template="exporter.env" --destination="$install_dir/exporter/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app-backend --action="start" --log_path="/var/log/$app/$app-backend.log" --wait_until="welcome to penpot" --timeout=300

ynh_systemctl --service=$app-exporter --action="start" --log_path="/var/log/$app/$app-exporter.log" --wait_until="redis connection established"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
