#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app-backend >/dev/null
then
    ynh_script_progression --message="Removing $app-backend service integration..."
    yunohost service remove $app-backend
    ynh_remove_systemd_config --service="$app-backend"
fi

if ynh_exec_warn_less yunohost service status $app-exporter >/dev/null
then
    ynh_script_progression --message="Removing $app-exporter service integration..."
    yunohost service remove $app-exporter
    ynh_remove_systemd_config --service="$app-exporter"
fi

ynh_remove_nginx_config

ynh_remove_logrotate

ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
