#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app-backend >/dev/null; then
    yunohost service remove $app-backend
    ynh_config_remove_systemd"$app-backend"
fi

if ynh_hide_warnings yunohost service status $app-exporter >/dev/null; then
    yunohost service remove $app-exporter
    ynh_config_remove_systemd"$app-exporter"
fi

ynh_config_remove_nginx

ynh_config_remove_logrotate

ynh_redis_remove_db "$redis_db"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
