#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_systemctl --service=$app-backend --action="stop"
ynh_systemctl --service=$app-exporter --action="stop"

ynh_app_setting_set_default  --app=$app --key=telemetry_enabled --value=false

ynh_script_progression "Ensure downwards compatibility..."

if ynh_app_upgrading_from_version_before 2.13.3~ynh1; then
    ynh_safe_rm "$install_dir/.cache"
    ynh_safe_rm "$install_dir/jdk"
fi

ynh_script_progression "Installing dependencies..."

ynh_setup_source --dest_dir="$install_dir/jre" --source_id="jre"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/backend" --source_id="backend"
ynh_setup_source --dest_dir="$install_dir/exporter" --source_id="exporter"
ynh_replace --match="\"--font-render-hinting\x3dnone\"" --replace="\"--font-render-hinting\x3dnone\", \"--disable-gpu\", \"--no-zygote\"" --file="$install_dir/exporter/exporter/app.js"
if [ ! -L "$install_dir/.cache" ]; then
    ln -s "$install_dir/exporter/.cache" "$install_dir/"
fi

chown -R $app:$app "$install_dir"

ynh_setup_source --dest_dir="$install_dir/frontend"
chown -R $app:www-data "$install_dir/frontend"
chgrp www-data $install_dir

chmod -R o-rwx "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --template="backend.service" --service="$app-backend"
yunohost service add $app-backend --log="/var/log/$app/$app-backend.log"

ynh_config_add_systemd --template="exporter.service" --service="$app-exporter"
yunohost service add $app-exporter --log="/var/log/$app/$app-exporter.log"

ynh_config_add_logrotate "/var/log/$app/$app-backend.log"
ynh_config_add_logrotate "/var/log/$app/$app-exporter.log"

#=================================================
# RECONFIGURE THE APP (UPDATE CONF, APPLY MIGRATIONS...)
#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating database configuration..."

ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"

ynh_script_progression "Updating configuration..."

ynh_config_add --template="config.js" --destination="$install_dir/frontend/js/config.js"
chmod 755 "$install_dir/frontend/js/config.js"
chown $app:www-data "$install_dir/frontend/js/config.js"

ynh_config_add --template="environ" --destination="$install_dir/backend/environ"

ynh_config_add --template="exporter.env" --destination="$install_dir/exporter/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app-backend --action="start" --log_path="/var/log/$app/$app-backend.log" --wait_until="welcome to penpot" --timeout=300

ynh_systemctl --service=$app-exporter --action="start" --log_path="/var/log/$app/$app-exporter.log" --wait_until="redis connection established"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
